from . import (
    animation,
    application_cache,
    audits,
    background_service,
    cast,
    console,
    css,
    database,
    debugger,
    dom,
    dom_storage,
    emulation,
    fetch,
    headless_experimental,
    heap_profiler,
    inspector,
    layer_tree,
    log,
    media,
    network,
    overlay,
    page,
    performance,
    performance_timeline,
    profiler,
    runtime,
    security,
    service_worker,
    storage,
    target,
    tethering,
    tracing,
    web_audio,
)

event_parsers = {
    "Animation.animationCanceled": animation.AnimationCanceled,
    "Animation.animationCreated": animation.AnimationCreated,
    "Animation.animationStarted": animation.AnimationStarted,
    "ApplicationCache.applicationCacheStatusUpdated": application_cache.ApplicationCacheStatusUpdated,
    "ApplicationCache.networkStateUpdated": application_cache.NetworkStateUpdated,
    "Audits.issueAdded": audits.IssueAdded,
    "BackgroundService.recordingStateChanged": background_service.RecordingStateChanged,
    "BackgroundService.backgroundServiceEventReceived": background_service.BackgroundServiceEventReceived,
    "CSS.fontsUpdated": css.FontsUpdated,
    "CSS.mediaQueryResultChanged": css.MediaQueryResultChanged,
    "CSS.styleSheetAdded": css.StyleSheetAdded,
    "CSS.styleSheetChanged": css.StyleSheetChanged,
    "CSS.styleSheetRemoved": css.StyleSheetRemoved,
    "Cast.sinksUpdated": cast.SinksUpdated,
    "Cast.issueUpdated": cast.IssueUpdated,
    "DOM.attributeModified": dom.AttributeModified,
    "DOM.attributeRemoved": dom.AttributeRemoved,
    "DOM.characterDataModified": dom.CharacterDataModified,
    "DOM.childNodeCountUpdated": dom.ChildNodeCountUpdated,
    "DOM.childNodeInserted": dom.ChildNodeInserted,
    "DOM.childNodeRemoved": dom.ChildNodeRemoved,
    "DOM.distributedNodesUpdated": dom.DistributedNodesUpdated,
    "DOM.documentUpdated": dom.DocumentUpdated,
    "DOM.inlineStyleInvalidated": dom.InlineStyleInvalidated,
    "DOM.pseudoElementAdded": dom.PseudoElementAdded,
    "DOM.pseudoElementRemoved": dom.PseudoElementRemoved,
    "DOM.setChildNodes": dom.SetChildNodes,
    "DOM.shadowRootPopped": dom.ShadowRootPopped,
    "DOM.shadowRootPushed": dom.ShadowRootPushed,
    "DOMStorage.domStorageItemAdded": dom_storage.DomStorageItemAdded,
    "DOMStorage.domStorageItemRemoved": dom_storage.DomStorageItemRemoved,
    "DOMStorage.domStorageItemUpdated": dom_storage.DomStorageItemUpdated,
    "DOMStorage.domStorageItemsCleared": dom_storage.DomStorageItemsCleared,
    "Database.addDatabase": database.AddDatabase,
    "Emulation.virtualTimeBudgetExpired": emulation.VirtualTimeBudgetExpired,
    "HeadlessExperimental.needsBeginFramesChanged": headless_experimental.NeedsBeginFramesChanged,
    "Inspector.detached": inspector.Detached,
    "Inspector.targetCrashed": inspector.TargetCrashed,
    "Inspector.targetReloadedAfterCrash": inspector.TargetReloadedAfterCrash,
    "LayerTree.layerPainted": layer_tree.LayerPainted,
    "LayerTree.layerTreeDidChange": layer_tree.LayerTreeDidChange,
    "Log.entryAdded": log.EntryAdded,
    "Network.dataReceived": network.DataReceived,
    "Network.eventSourceMessageReceived": network.EventSourceMessageReceived,
    "Network.loadingFailed": network.LoadingFailed,
    "Network.loadingFinished": network.LoadingFinished,
    "Network.requestIntercepted": network.RequestIntercepted,
    "Network.requestServedFromCache": network.RequestServedFromCache,
    "Network.requestWillBeSent": network.RequestWillBeSent,
    "Network.resourceChangedPriority": network.ResourceChangedPriority,
    "Network.signedExchangeReceived": network.SignedExchangeReceived,
    "Network.responseReceived": network.ResponseReceived,
    "Network.webSocketClosed": network.WebSocketClosed,
    "Network.webSocketCreated": network.WebSocketCreated,
    "Network.webSocketFrameError": network.WebSocketFrameError,
    "Network.webSocketFrameReceived": network.WebSocketFrameReceived,
    "Network.webSocketFrameSent": network.WebSocketFrameSent,
    "Network.webSocketHandshakeResponseReceived": network.WebSocketHandshakeResponseReceived,
    "Network.webSocketWillSendHandshakeRequest": network.WebSocketWillSendHandshakeRequest,
    "Network.webTransportCreated": network.WebTransportCreated,
    "Network.webTransportConnectionEstablished": network.WebTransportConnectionEstablished,
    "Network.webTransportClosed": network.WebTransportClosed,
    "Network.requestWillBeSentExtraInfo": network.RequestWillBeSentExtraInfo,
    "Network.responseReceivedExtraInfo": network.ResponseReceivedExtraInfo,
    "Network.trustTokenOperationDone": network.TrustTokenOperationDone,
    "Overlay.inspectNodeRequested": overlay.InspectNodeRequested,
    "Overlay.nodeHighlightRequested": overlay.NodeHighlightRequested,
    "Overlay.screenshotRequested": overlay.ScreenshotRequested,
    "Overlay.inspectModeCanceled": overlay.InspectModeCanceled,
    "Page.domContentEventFired": page.DomContentEventFired,
    "Page.fileChooserOpened": page.FileChooserOpened,
    "Page.frameAttached": page.FrameAttached,
    "Page.frameClearedScheduledNavigation": page.FrameClearedScheduledNavigation,
    "Page.frameDetached": page.FrameDetached,
    "Page.frameNavigated": page.FrameNavigated,
    "Page.documentOpened": page.DocumentOpened,
    "Page.frameResized": page.FrameResized,
    "Page.frameRequestedNavigation": page.FrameRequestedNavigation,
    "Page.frameScheduledNavigation": page.FrameScheduledNavigation,
    "Page.frameStartedLoading": page.FrameStartedLoading,
    "Page.frameStoppedLoading": page.FrameStoppedLoading,
    "Page.downloadWillBegin": page.DownloadWillBegin,
    "Page.downloadProgress": page.DownloadProgress,
    "Page.interstitialHidden": page.InterstitialHidden,
    "Page.interstitialShown": page.InterstitialShown,
    "Page.javascriptDialogClosed": page.JavascriptDialogClosed,
    "Page.javascriptDialogOpening": page.JavascriptDialogOpening,
    "Page.lifecycleEvent": page.LifecycleEvent,
    "Page.loadEventFired": page.LoadEventFired,
    "Page.navigatedWithinDocument": page.NavigatedWithinDocument,
    "Page.screencastFrame": page.ScreencastFrame,
    "Page.screencastVisibilityChanged": page.ScreencastVisibilityChanged,
    "Page.windowOpen": page.WindowOpen,
    "Page.compilationCacheProduced": page.CompilationCacheProduced,
    "Performance.metrics": performance.Metrics,
    "PerformanceTimeline.timelineEventAdded": performance_timeline.TimelineEventAdded,
    "Security.certificateError": security.CertificateError,
    "Security.visibleSecurityStateChanged": security.VisibleSecurityStateChanged,
    "Security.securityStateChanged": security.SecurityStateChanged,
    "ServiceWorker.workerErrorReported": service_worker.WorkerErrorReported,
    "ServiceWorker.workerRegistrationUpdated": service_worker.WorkerRegistrationUpdated,
    "ServiceWorker.workerVersionUpdated": service_worker.WorkerVersionUpdated,
    "Storage.cacheStorageContentUpdated": storage.CacheStorageContentUpdated,
    "Storage.cacheStorageListUpdated": storage.CacheStorageListUpdated,
    "Storage.indexedDBContentUpdated": storage.IndexedDBContentUpdated,
    "Storage.indexedDBListUpdated": storage.IndexedDBListUpdated,
    "Target.attachedToTarget": target.AttachedToTarget,
    "Target.detachedFromTarget": target.DetachedFromTarget,
    "Target.receivedMessageFromTarget": target.ReceivedMessageFromTarget,
    "Target.targetCreated": target.TargetCreated,
    "Target.targetDestroyed": target.TargetDestroyed,
    "Target.targetCrashed": target.TargetCrashed,
    "Target.targetInfoChanged": target.TargetInfoChanged,
    "Tethering.accepted": tethering.Accepted,
    "Tracing.bufferUsage": tracing.BufferUsage,
    "Tracing.dataCollected": tracing.DataCollected,
    "Tracing.tracingComplete": tracing.TracingComplete,
    "Fetch.requestPaused": fetch.RequestPaused,
    "Fetch.authRequired": fetch.AuthRequired,
    "WebAudio.contextCreated": web_audio.ContextCreated,
    "WebAudio.contextWillBeDestroyed": web_audio.ContextWillBeDestroyed,
    "WebAudio.contextChanged": web_audio.ContextChanged,
    "WebAudio.audioListenerCreated": web_audio.AudioListenerCreated,
    "WebAudio.audioListenerWillBeDestroyed": web_audio.AudioListenerWillBeDestroyed,
    "WebAudio.audioNodeCreated": web_audio.AudioNodeCreated,
    "WebAudio.audioNodeWillBeDestroyed": web_audio.AudioNodeWillBeDestroyed,
    "WebAudio.audioParamCreated": web_audio.AudioParamCreated,
    "WebAudio.audioParamWillBeDestroyed": web_audio.AudioParamWillBeDestroyed,
    "WebAudio.nodesConnected": web_audio.NodesConnected,
    "WebAudio.nodesDisconnected": web_audio.NodesDisconnected,
    "WebAudio.nodeParamConnected": web_audio.NodeParamConnected,
    "WebAudio.nodeParamDisconnected": web_audio.NodeParamDisconnected,
    "Media.playerPropertiesChanged": media.PlayerPropertiesChanged,
    "Media.playerEventsAdded": media.PlayerEventsAdded,
    "Media.playerMessagesLogged": media.PlayerMessagesLogged,
    "Media.playerErrorsRaised": media.PlayerErrorsRaised,
    "Media.playersCreated": media.PlayersCreated,
    "Console.messageAdded": console.MessageAdded,
    "Debugger.breakpointResolved": debugger.BreakpointResolved,
    "Debugger.paused": debugger.Paused,
    "Debugger.resumed": debugger.Resumed,
    "Debugger.scriptFailedToParse": debugger.ScriptFailedToParse,
    "Debugger.scriptParsed": debugger.ScriptParsed,
    "HeapProfiler.addHeapSnapshotChunk": heap_profiler.AddHeapSnapshotChunk,
    "HeapProfiler.heapStatsUpdate": heap_profiler.HeapStatsUpdate,
    "HeapProfiler.lastSeenObjectId": heap_profiler.LastSeenObjectId,
    "HeapProfiler.reportHeapSnapshotProgress": heap_profiler.ReportHeapSnapshotProgress,
    "HeapProfiler.resetProfiles": heap_profiler.ResetProfiles,
    "Profiler.consoleProfileFinished": profiler.ConsoleProfileFinished,
    "Profiler.consoleProfileStarted": profiler.ConsoleProfileStarted,
    "Profiler.preciseCoverageDeltaUpdate": profiler.PreciseCoverageDeltaUpdate,
    "Runtime.bindingCalled": runtime.BindingCalled,
    "Runtime.consoleAPICalled": runtime.ConsoleAPICalled,
    "Runtime.exceptionRevoked": runtime.ExceptionRevoked,
    "Runtime.exceptionThrown": runtime.ExceptionThrown,
    "Runtime.executionContextCreated": runtime.ExecutionContextCreated,
    "Runtime.executionContextDestroyed": runtime.ExecutionContextDestroyed,
    "Runtime.executionContextsCleared": runtime.ExecutionContextsCleared,
    "Runtime.inspectRequested": runtime.InspectRequested,
}
